import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Connexion' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email' }).fill('victoria@gmail');
  await page.getByRole('textbox', { name: 'Email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email' }).fill('victoria@gmail.');
  await page.getByRole('textbox', { name: 'Email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Email' }).fill('victoria@gmail.com');
  await page.getByRole('textbox', { name: '••••••••' }).click();
  await page.getByRole('textbox', { name: '••••••••' }).click();
  await page.getByRole('textbox', { name: '••••••••' }).press('CapsLock');
  await page.getByRole('textbox', { name: '••••••••' }).fill('S');
  await page.getByRole('textbox', { name: '••••••••' }).press('CapsLock');
  await page.getByRole('textbox', { name: '••••••••' }).fill('Sourire@');
  await page.getByRole('textbox', { name: '••••••••' }).press('CapsLock');
  await page.getByRole('textbox', { name: '••••••••' }).fill('Sourire@2001');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('button', { name: 'Missions' }).click();
  await page.getByRole('button', { name: 'Postuler' }).click();
  await page.getByRole('button', { name: 'Commencer maintenant' }).click();
  await page.goto('http://localhost:3000/dashboard/candidats/missions/15/application');
  await page.getByRole('button', { name: 'DÉMARRER L\'ÉVALUATION' }).click();
  await page.getByRole('main').filter({ hasText: 'CandidatureValidez votre' }).getByRole('main').click();
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).first().click();
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).first().click();
  await page.getByText('Qu\'est-ce qui vous motive à').click();
  await page.getByText('Qu\'est-ce qui vous motive à').click();
  await page.getByText('Qu\'est-ce qui vous motive à').click();
  await page.getByText('Qu\'est-ce qui vous motive à').click();
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).first().click();
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).first().click();
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).first().fill('');
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).first().press('CapsLock');
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).first().fill('J');
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).first().press('CapsLock');
  await page.getByText('J', { exact: true }).fill('J\'ai toujours voulu occuper ce poste');
  await page.getByText('J', { exact: true }).press('CapsLock');
  await page.getByText('J', { exact: true }).fill('J\'ai toujours voulu occuper ce poste. Je suis interessé et très motivé à rejoindre votre équipe pour mettre mon savoir faire à votre service');
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).nth(1).fill('J');
  await page.getByText('J', { exact: true }).press('CapsLock');
  await page.getByText('J', { exact: true }).fill('J');
  await page.getByText('J', { exact: true }).press('CapsLock');
  await page.getByText('J', { exact: true }).fill('Je suis disponible et en mesure de commencer dès que ce sera possible');
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).nth(2).press('CapsLock');
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).nth(2).fill('E');
  await page.getByRole('textbox', { name: 'Votre réponse ici...' }).nth(2).press('CapsLock');
  await page.getByText('E', { exact: true }).fill('En me créant un planning bien défini');
  await page.getByText('En me créant un planning bien').click();
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').press('ArrowLeft');
  await page.getByText('En me créant un planning bien').fill('En établissant un planning bien défini');
  await page.getByText('En établissant un planning').click();
  await page.getByText('En établissant un planning').click();
  await page.getByText('En établissant un planning').fill('En établissant un planning bien défini');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').fill('En établissant un planning bien défini et en le suivant ');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowLeft');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').press('ArrowRight');
  await page.getByText('En établissant un planning').fill('En établissant un planning bien défini en foction des exigences du poste et en le suivant ');
  await page.getByText('En établissant un planning').click();
  await page.getByText('En établissant un planning').fill('En établissant un planning bien défini en foction des exigences du poste et en le suivant scrpuleusement');
  await page.getByText('En établissant un planning').press('CapsLock');
  await page.getByText('En établissant un planning').fill('En établissant un planning bien défini en foction des exigences du poste et en le suivant scrpuleusement.');
  await page.getByText('En établissant un planning').press('CapsLock');
  await page.getByRole('button', { name: 'TERMINER' }).click();
  await page.getByRole('button', { name: 'Retour aux missions' }).click();
  await page.getByRole('button', { name: 'Tableau de bord' }).click();
  await page.getByText('MarketteurSONY • Expire dans 17 joursEn Attente').click();
  await page.getByRole('button', { name: 'CORNEILLE Victoria Espace' }).click();
  await page.getByRole('link', { name: 'Mon profil' }).click();
});